[workspace]
preview = ["pixi-build"]
channels = ["KEKE046", "PisonJay", "conda-forge"]
platforms = ["linux-64"]

[package]
name = "libgloss-uart"
version = "1.0.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version="0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[dependencies]
riscv-tools = ">=1.0.8,<2"
spike = ">=1.1.0,<2"
dtc = ">=1.7.2,<2"
